### ISSUE TITLE
Québec stuff

### ISSUE THREAD

**Issue by millette** [accessibility/multilingual#2]
https://www.tresor.gouv.qc.ca/ressources-informationnelles/architecture-dentreprise-gouvernementale/standards-et-normes/accessibilite-du-web/

Include links to [Standard sur l’accessibilité des sites Web(SGQRI 008 2.0)](https://www.tresor.gouv.qc.ca/fileadmin/PDF/ressources_informationnelles/AccessibiliteWeb/standard-access-web.pdf) [PDF] and more.

**Comment by mgifford** [comment]
Thanks @millette - sorry for the very, very late response. Not sure how I missed this. Where should this go? I'm so bloody Anglo..  Really appreciate this feedback. 

Hope you're doing well Robin

**Comment by millette** [comment]
Under [Documentation](https://github.com/accessibility/multilingual/blob/master/Fran%C3%A7ais.md#documentation).

Hope you're well too :-)

**Comment by mgifford** [comment]
Added here https://github.com/accessibility/multilingual/blob/master/Fran%C3%A7ais.md

And yes, doing fine here.
